### ISSUE TITLE
Issue with starting Fury at ng serve

### ISSUE THREAD

**Issue by dodegaard** [nikita-volkov/Fury#2]
I have a fresh install of npm, typescript and node and am getting this error in starting the app. Can you help me with steps to get the initial build running?  This is on MacOSX Sierra 10.12.3 . I did purchase support with the template.  Thanks.  

`dodegaard-MBA:monitorsite dodegaard$ ng serve
Your global Angular CLI version (1.0.0) is greater than your local
version (1.0.0-rc.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
dodegaard-MBA:monitorsite dodegaard$ npm start

> Fury@2.2.0 start /Users/dodegaard/Documents/MonitorSite
> ng serve

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Fury@2.2.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Fury@2.2.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Fury package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Fury
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Fury
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dodegaard/Documents/MonitorSite/npm-debug.log
dodegaard-MBA:monitorsite dodegaard$ npm update
dodegaard-MBA:monitorsite dodegaard$ npm start

> Fury@2.2.0 start /Users/dodegaard/Documents/MonitorSite
> ng serve

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (/Users/dodegaard/Documents/MonitorSite/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Fury@2.2.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Fury@2.2.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Fury package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Fury
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Fury
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dodegaard/Documents/MonitorSite/npm-debug.log`

**Comment by nikita-volkov** [comment]
Unfortunately I no longer support JavaScript libraries.

**Comment by dodegaard** [comment]
Are you no longer working with "visurel" at Themeforest?

**Comment by nikita-volkov** [comment]
Never have :)

**Comment by dodegaard** [comment]
Thanks.  I will tell the authors to update their pointer to your lib for their support :)
